### ISSUE TITLE
Add a plugin to remove unused CSS rules

### ISSUE THREAD

**Issue by nfrankel** [alexo/wro4j#222]
Extra CSS rules are one of the problem identified by Chrome's auditing. It would be great if wro4j provided such a plugin.

The only hint of an existing solution I have is [UnCSS](https://github.com/giakki/uncss) but there might be better solutions.

**Comment by alexo** [comment]
I'll move this issue to the new project location: https://github.com/wro4j/wro4j

**Comment by nfrankel** [comment]
Thanks!
Perhaps, you should close this project, it's quite misleading.

**Comment by alexo** [comment]
@nfrankel I agree that it is misleading. However, it contains a large number of issues which require manual migration... Is it possible to close it without losing this kind of data?

**Comment by nfrankel** [comment]
I have no idea... Probably there's an API for that.
