### ISSUE TITLE
Provide ways to specify Closure params

### ISSUE THREAD

**Issue by lauterry** [alexo/wro4j#89]
Hi, 

Wro4J supports Closure Compiler but doesn't provide a way to specify Closure options such as <code>language_in</code> and others in the pom.xml file

Best regards

**Comment by M3lkior** [comment]
Hello Alexo,

I have the same need. It is possible to plan a wro4j update to generalize options in processor ?


With a syntax like this :

preProcessors=cssUrlRewriting,lessCssImport,semicolonAppender
postProcessors=less4j[option1=value, option2=value],yuiCssMin,googleClosureSimple[language_in=ECMASCRIPT3, language_out=ECMASCRIPT5]

With a simple treatment to avoid wrong values ?

**Comment by alexo** [comment]
I'm thinking about something the following format:

    processor.googleClosureSimple.options=key1=value1,key2=value2

or

    processor.googleClosureSimple.options={key1:value1,key2:value2}

**Comment by M3lkior** [comment]
Yeah, 

processor.googleClosureSimple.options={key1:value1,key2:value2} seems to be a good solution :)

**Comment by vijayranker** [comment]
is there any update on this feature?

**Comment by vijayranker** [comment]
Mar 14, 2017 4:49:13 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /js/__v2/app/ad/bidderConfig.js:256: ERROR - Parse error. IE8 (and below) will parse trailing commas in array and object literals incorrectly. If you are targeting newer versions of JS, set the appropriate language_in option.
                                },
                                 ^

for me its failing with above error

**Comment by alexo** [comment]
The project was migrated to a new location. Any discussion related to this issue is located here:
https://github.com/wro4j/wro4j/issues/671
